### PR TITLE
Fix use_sim_time not modifying clock

### PR DESCRIPTION
**Pull request by jacobperron**
Previously, when attaching a node that has 'use_sim_time' set to true,
we were not setting ROS time on any previously attached clocks or creating a subscription
to the /clock topic. This change fixes that by calling the TimeSource setter.

Added unit tests that fail without this fix.

### CODE REVIEW

**Comment by jacobperron** [comment]
I wonder if there was an update in colcon or the ros-tooling action that changed the behavior of "colcon_defaults". I don't see any reason why CI should start failing with the changes in this PR.

**Review by ivanpauno — APPROVED** [review]
LGTM!

**Comment by ivanpauno** [comment]
It's strange that it's only not finding "test_interface_files", and it only fails in the job that uses java 6, which shouldn't make a difference.

**Comment by ivanpauno** [comment]
is `test_interface_files` installed though?

I don't see it being installed as part of `ros-rolling-desktop`, and I don't see it in our .repos files.
Maybe we need to add it there (?).

If that's the case, I'm not sure why the job was passing before :smile:

**Comment by jacobperron** [comment]
Fixed CI in https://github.com/osrf/ros2_java/pull/89 and rebased this PR.

**Pull request merged**
