### PR TITLE
Fix source 6 warnings

### PR DESCRIPTION
**Pull request by ivanpauno**
Replaces https://github.com/osrf/ros2_java/pull/66 (I opened that one in a fork by accident).

I hope this workflow config works :grimacing:

### CODE REVIEW

**Comment by ivanpauno** [comment]
If we need to specify `-target` `-source` in Android as commented [here](https://github.com/osrf/ros2_java/pull/66#issuecomment-840129977), we can readd that in the future.

I'm using `--release` in the github workflows, because it does the right thing TM.
See https://stackoverflow.com/questions/43102787/what-is-the-release-flag-in-the-java-9-compiler.

**Comment by ivanpauno** [comment]
mmm, not sure why the build failed, I'm going to double check

**Comment by ivanpauno** [comment]
Well, actually our code is not fully compatible with java 6 (`java.time.Duration` doesn't exist).
`--release 6` is more strict that passing `-source 1.6` `-target 1.6`.

I will use the later, because I think that `java.time.Duration` is available in android anyways ... (either through the  [ThreeTen backport](https://github.com/JakeWharton/ThreeTenABP) or through the android gradle 4.0 plugin).

**Comment by ivanpauno** [comment]
CI now looks ok (same failure that we were having before and that #70 should fix :smiley: )

**Review by jacobperron — APPROVED** [review]
I've rebased the changes.

**Comment by jacobperron** [comment]
https://github.com/osrf/ros2_java/pull/76 should fix the infrastructure issue.

**Comment by ivanpauno** [comment]
Rebasing again after #76 was merged.

**Pull request merged**
